(package "company-kaomoji"
         "0.1.0"
         "company-mode backend for kaomoji")

(website-url "https://github.com/jcs-elpa/company-kaomoji")
(keywords "matching" "kaomoji")

(package-file "company-kaomoji.el")

(source "jcs-elpa")

(depends-on "emacs" "26.1")
(depends-on "company")
(depends-on "kaomoji")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
